kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    version: {{ .Values.image.tag }}
    app: {{ .Values.name }}
    tier: computing
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
    tier: computing
  ports:
  - name: http-{{ .Values.name }}
    protocol: TCP
    port: {{ .Values.service.httpport }}
    targetPort: http-{{ .Values.name }}
  - name: https-{{ .Values.name }}
    protocol: TCP
    port: {{ .Values.service.httpsport }}
    targetPort: https-{{ .Values.name }}
